### ISSUE TITLE
Parser fails on some expressions containing '#'

### ISSUE THREAD

**Issue by simonfxr** [mads-hartmann/bash-language-server#100]
The parser fails on some expressions where '#' should not be interpreted as the start of a comment.
Examples:
- Interpret number in a certain base: `dec=$((10#$x))`
- Referring to the number of positional parameters : `last=${!#}`, `n=${#}`

This language server is really useful in working with large collections of shell scripts! Fixing these corner cases would be great!

**Comment by skovhus** [comment]
Thanks! This is an error in the underlying parser. 

Can you create a ticket here: https://github.com/tree-sitter/tree-sitter-bash ?

**Comment by simonfxr** [comment]
[Done](https://github.com/tree-sitter/tree-sitter-bash/issues/41)
