### ISSUE TITLE
 'missing field `kind`' when trying to list document symbols

### ISSUE THREAD

**Issue by tterranigma** [mads-hartmann/bash-language-server#108]
I am using neovim with the LanguageClient-neovim plugin. I have opened a simple script file. There, I call the `LanguageClient_textDocument_documentSymbol()` function that is supposed to list the symbols in the document. When I do that, I get a message:

```
[LC] missing field `kind`
```

This is not a code error, it is captured and displayed properly as a message by the LanguageClient plugin.

I am not sure this is a bug with the language server (on vscode it works ok) but I thought I would ask here first.

**Comment by skovhus** [comment]
@tterranigma Can you see if upgrading fixes this issue?

Upgrade by running:
`npm install -g bash-language-server`
