### ISSUE TITLE
Strict POSIX mode

### ISSUE THREAD

**Issue by FlyingWombat** [mads-hartmann/bash-language-server#118]
I know this is ***bash***-language-server, but I'm wondering it would be in-scope to add a strict POSIX mode to check script compatibility with shells like `dash` and regular `sh`.

As the name suggests, this mode would flag any deviations from the POSIX shell standard.

This would pretty much be solved by #104, since `shellcheck` already has a mode for linting strict POSIX shell, with its `--shell` option.  
Another useful tool for this might be `checkbashisms` from the [Debian DevScripts repo](https://packages.qa.debian.org/d/devscripts.html). ([Arch package](https://www.archlinux.org/packages/community/any/checkbashisms/) for reference)

**Comment by skovhus** [comment]
@mads-hartmann do you know if the tree-sitter-bash would support this?

**Comment by mads-hartmann** [comment]
Given that shellcheck already has support for this and has a great VSCode extension I think it's outside the scope of this project to check for POSIX compliance 🙂
