### ISSUE TITLE
Support running bash-language-server in Docker for Windows

### ISSUE THREAD

**Issue by deimi** [mads-hartmann/bash-language-server#121]
It would be neat to run the linux version of bash-language-server in Docker for Windows, instead of having to install it on the Windows host PC with all it dependencies.

I have tried to do it already, but I failed. I don't have that much experience with Javascript and VSCode extensions. (See https://github.com/deimi/bash-language-server-docker for my docker image where bash-language-server can be executed)
At the beginning I was not able to execute the docker container ("docker run -i --rm bash-language-server:latest") via the vscode client. The reason was that the client is using child_process_1.execFile. I temporary changed it to child_process_1.exec and the client can execute the server inside docker.
But then I got into the next problem. The client tries to check the version of the server, but the result is always "0.0.0". I think there is something wrong with stdout from docker to client, but I'm not sure and after much trying I got stuck.

Maybe someone else has some good ideas to get this running? At the moment I'm not even near to test the real LSP stuff....

**Comment by skovhus** [comment]
Unfortunately, this is not something we have the resources to do. I'm going to close this issue for now, but let me know if you progress on the feature. It would be neat.

**Comment by rcjsuen** [comment]
@deimi I tried building your Docker image just now and `-v` gave me `Version is 1.6.0` so you should try it again. Perhaps the latest changes from @skovhus have affected this in some way.

**Comment by deimi** [comment]
@rcjsuen As soon as I can spare some time, I will give it a try.  
@skovhus  In middle-term I want to realize this and will push it to this repo, but it seems that at first I have to sniff a little bit into the language server standard to solve this.

**Comment by skovhus** [comment]
Thanks! Actually, we plan to release the vscode client including the server very soon. All installed inside vscode. 📦

I assume this would be best solution for this. Before version 1.6.0 we could do this, as our parser depended on native bindings. But now we can ship it all together.

**Comment by deimi** [comment]
Oh that's by far even better!!! My actual intention was to use the language server with vscode, but without taking care of handling multiple versions of the dependencies in my host system.  
Now the pressure is gone and I can get the docker version running just out of curiosity :wink:
