### ISSUE TITLE
Installation fails with node.js 12.x

### ISSUE THREAD

**Issue by jmooring** [mads-hartmann/bash-language-server#124]
Command:

```bash
npm i -g bash-language-server
```

Log file:
[2019-04-27T12_00_31_775Z-debug.log](https://github.com/mads-hartmann/bash-language-server/files/3123851/2019-04-27T12_00_31_775Z-debug.log)

**Comment by Jackson-soft** [comment]
same issues

**Comment by pradeepvrd** [comment]
I ran in to the same issue. Looks like the `tree-sitter` dependency no longer compiles with node 12. See below issue:

https://github.com/tree-sitter/node-tree-sitter/issues/46

**Comment by esn89** [comment]
I am also getting something similar:
https://pastebin.com/iujgKnBD

**Comment by skovhus** [comment]
We have just released a new version of `bash-language-server` (1.6.0) that:
- supports node > 8 (including 12)
- should remove all installation issues caused by node-gyp and native bindings

To upgrade run:
```
npm i -g bash-language-server
```

Let us know if this works for you. Thanks :)

**Comment by skovhus** [comment]
@pradeepvrd @Jackson-soft @jmooring let me know if this works for you.

**Comment by oblitum** [comment]
@skovhus is node-gyp necessary to be installed or was that requirement also removed?

**Comment by skovhus** [comment]
Node-gyp shouldn’t be necessary.

**Comment by Jackson-soft** [comment]
work,Thank you for your work
@skovhus

**Comment by oblitum** [comment]
Well nice, thanks, it just works now.

**Comment by skovhus** [comment]
I'm glad it works! Next step for the vscode extension is to remove the server install step by bundling it into the extension. :)

**Comment by oblitum** [comment]
That's nice, even though I never touched vscode :) I use it on neovim with coc.nvim.

**Comment by jmooring** [comment]
@skovhus 
```npm i -g bash-language-server``` work as expected; no problems. Thank you.
