### ISSUE TITLE
Permission Denied on Atom Client Install Setup

### ISSUE THREAD

**Issue by diveyez** [mads-hartmann/bash-language-server#125]
root@UNKNOWN:/usr/lib# git clone git@github.com:mads-hartmann/ide-bash && cd ide-bash
Cloning into 'ide-bash'...
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by diveyez** [comment]
Even after I setup this, everytime I open Atom it says the language server is not found. Even with the path variable correctly configured.

**Comment by skovhus** [comment]
Closed due to inactivity.
