### ISSUE TITLE
Stop output window automatically opening

### ISSUE THREAD

**Issue by robertmarkbram** [mads-hartmann/bash-language-server#128]
This is driving me crazy but just started happening today.. anytime I work on a file the output window for BASH IDE opens.. it always starts with text like:

```
Initialized server v. 1.5.6 for file:///c%3A/Users/robert.bram/work/notes
Analyzing file://c:\Users\robert.bram\work\notes\bin\filexxx.sh
Analyzing file://c:\Users\robert.bram\work\notes\bin\fileyyy.sh
```

**Comment by skovhus** [comment]
That sounds weird. Could it be a configuration option in vs code, that you by mistake enabled?

**Comment by robertmarkbram** [comment]
I googled VS Code auto opening the output console, and the responses I read say that it is linked to whatever extension is writing to that console - and VS Code says it's a bash IDE console.. so I am not sure what conf options relate to this.

**Comment by skovhus** [comment]
Thanks. Can I get you to record a gif/movie showing the problem? That might make it easier for us to debug.

You can depending on your OS, use https://licecap.en.softonic.com/ for it.

Thanks.

**Comment by skovhus** [comment]
@robertmarkbram do you still have this problem? If so then please reopen with a gif/screenshot.
