### ISSUE TITLE
Create setting to disable/enable parse error reporting

### ISSUE THREAD

**Issue by mads-hartmann** [mads-hartmann/bash-language-server#13]
Until we've perfected the Bash tree-sitter grammar it would be nice to be able to disable showing the parse errors.

**Comment by skovhus** [comment]
Should it be a configuration? Or how do you envision it?

**Comment by mads-hartmann** [comment]
@skovhus I think making it a configuration would be a nice solution :)

**Comment by christopherdwhite** [comment]
An option would be really helpful given that ShellCheck is available in other extensions for VSC (and I'm sure others) and seems like a pretty mature tool.

PS: Thank you so much for creating this, it's so fantastic to have proper symbols for Bash scripts, I very nearly gave up on VSC for shell scripts and switched back to Sublime before finding this!

**Comment by mads-hartmann** [comment]
This has been fixed in release bash-language-server 1.4.1 and version 1.3.2 of the vscode client.
