### ISSUE TITLE
Your npm dependency cannot be installed with node 12.6.0

### ISSUE THREAD

**Issue by chadlavi-casebook** [mads-hartmann/bash-language-server#141]
get errors from tree-sitter when trying to install `bash-language-server`. It renders the Bash IDE vscode plugin useless.

**Comment by skovhus** [comment]
Yes, we are blocked on an upstream issue. : /

**Comment by oblitum** [comment]
Sadly, node-tree-sitter seems quite inactive, maybe the fix won't along soon.

**Comment by skovhus** [comment]
We have just released a new version of `bash-language-server` (1.6.0) that:
- supports node > 8 (including 12)
- should remove all installation issues caused by node-gyp and native bindings

To upgrade run:
```
npm i -g bash-language-server
```

Let us know if this works for you. Thanks :)

**Comment by esn89** [comment]
Thanks, so far no issues for me!
