### ISSUE TITLE
Parsing fails for expansion: ${s#+( )} (or with %) (trim string)

### ISSUE THREAD

**Issue by Tatsh** [mads-hartmann/bash-language-server#152]
This is something I use for trimming strings of whitespace at the end and beginning:

```sh
filename=${filename##+( )}
filename=${filename%%+( )}
```

**Comment by skovhus** [comment]
Thanks for reporting this issue. It seems to be a grammar issue.

Can you create an issue over here: https://github.com/tree-sitter/tree-sitter-bash
