### ISSUE TITLE
Failed to parse expression for $[

### ISSUE THREAD

**Issue by gullevek** [mads-hartmann/bash-language-server#153]
Code example

foobar=$[$bar+$foo]

Says $[ has error, but this is valid bash syntax

on commandline (macos or linux)
$> bar=1;
$> foo=2;
$> foobar=$[$bar+$foo];
$> echo $foobar;
3

**Comment by skovhus** [comment]
Thanks for reporting. This is probably a limitation in the underlying gramma (https://github.com/tree-sitter/tree-sitter-bash).

This might be as `$[]` is deprecated in favor of `$()`.

The manpage for bash v3.2.48 says:

```
[...] The format for arithmetic expansion is:

     $((expression))
The old format $[expression] is deprecated and will be removed in upcoming versions of bash.
```

So `$[...]` is the old syntax that should not be used anymore.
