### ISSUE TITLE
Completion of exacutables in PATH with tilde

### ISSUE THREAD

**Issue by dmerc** [mads-hartmann/bash-language-server#155]
Given `PATH=/usr/bin:~/bin` only the executables in `/usr/bin` are shown in auto completion.

I found that its due to problem in executables.ts, function findExecutablesInPath,
the call to fs.lstat doesnt expand tilde in the path.

I suggest just adding tilde expansion, since nodejs doesnt handle it automatically

**Comment by skovhus** [comment]
That makes sense, thanks. Do you want to give it a try in a PR?

**Comment by dmerc** [comment]
ok will do
