### ISSUE TITLE
exit code 7

### ISSUE THREAD

**Issue by truesilver92** [mads-hartmann/bash-language-server#172]
What does exit code 7 mean?

**Comment by skovhus** [comment]
> What does exit code 7 mean?

Where do you experience this exit code?

**Comment by truesilver92** [comment]
It was during useage of emacs with the lsp-mode package. I was wondering what the error code means so that I could narrow down which software is actually causing the error and why.

It happens after opening either of these 2 files.

```sh
#! /bin/sh

set -e
set -x

if [ -z "$RESTIC_REPOSITORY" ]; then
    echo 'ERROR: variable $RESTIC_REPOSITORY must be set'
    exit 1
fi

if [ -z "$RESTIC_PASSWORD" ]; then
    echo 'ERROR: variable $RESTIC_PASSWORD must be set'
    exit 1
fi

if [ -z "$BACKUP_HOSTNAME" ]; then
    echo 'ERROR: variable $BACKUP_HOSTNAME must be set'
    exit 1
fi

echo "$BACKUP_CRON /backup.sh >> /var/log/backup.log 2>&1" > /etc/crontabs/root
touch /var/log/backup.log

crond && tail -f /var/log/backup.log

```

```sh
#! /bin/bash

set -e

mkdir -p /backup

echo_header() {
    printf "\n-----\n\n"
    echo "$1: $(date)"
    printf "\n-----\n\n"
}

if [[ -n "$BACKUP_POSTGRES_DSN" ]]; then
    echo_header "starting postgres dump"
    pg_dump -w -d $BACKUP_POSTGRES_DSN -c --if-exists $BACKUP_POSTGRES_OPTS | xz -zc9e - > /backup/backup_postgres_$PGDATABASE.sql.xz
    echo_header "finished postgres dump"
fi

if [[ -n "$MYSQL_HOST" ]]; then
   echo_header "starting mysql dump"
   mysqldump --skip-comments --host="$MYSQL_HOST"  --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" $BACKUP_MYSQL_OPTS "$MYSQL_DATABASE" | xz -zc9e - > /backup/backup_mysql_$MYSQL_DATABASE.sql.xz
   echo_header "finished mysql dump"
fi

echo_header "running custom scripts"
find /scripts -maxdepth 1 -executable -type f -print0|xargs -0 -I % sh -c %
echo_header "finished running custom scripts"

echo_header "starting restic backup"
restic backup --verbose --host "$BACKUP_HOSTNAME" /backup
echo_header "finished restic backup"

```

**Comment by skovhus** [comment]
I can't see how any of these would make the language server fail. Are you able to get more than the exit code from the LSP? Can you start the process up manually in a terminal, and get the output.

According to https://nodejs.org/api/process.html#process_exit_codes, then if the code codes from nodejs (which is the runtime of the LSP) exit code 7 is an uncaught exception.

**Comment by truesilver92** [comment]
Sorry about the slow response, and not taking the time to make it minimally reproducable. I'm not sure what was causing the error. It is gone now (I must have messed with the config more). If I see it in the future I'll come back to this with info on how to reproduce it.
