### ISSUE TITLE
link <bash language server> on Marketplace goes to the 404 page

### ISSUE THREAD

**Issue by almaceleste** [mads-hartmann/bash-language-server#179]
The link in the `Bash IDE` extension description on Marketplace goes to the wrong page (404 error): 
> Visual Studio Code extension utilizing the [bash language server](https://github.com/mads-hartmann/bash-language-server/blob/master/bash-lsp)...

**Comment by skovhus** [comment]
Thanks for reporting this. Will be fixed in the next release.
