### ISSUE TITLE
Should suggest keywords

### ISSUE THREAD

**Issue by Eugeny** [mads-hartmann/bash-language-server#182]
bash-language-server should include bash keywords in the suggestions list, otherwise pressing Enter at the end of this line will substitute `gsf-office-thumbnailer`

![image](https://user-images.githubusercontent.com/161476/74932605-85c1b400-53e2-11ea-9cb6-f853fc7635af.png)

**Comment by skovhus** [comment]
Thanks for reporting this. It has been fixed in `bash-language-server@1.10.0` and the latest VS Code client (version 1.7.0).

**Comment by Eugeny** [comment]
Thanks a lot for the fast turnaround!
