### ISSUE TITLE
Incompatible language version

### ISSUE THREAD

**Issue by przepompownia** [mads-hartmann/bash-language-server#196]
I cannot run the current version of the server with CoC.
```
[coc.nvim] Request initialize failed with message: Incompatible language version 11. Compatibility range 9 through 10.
[coc.nvim] Server bash failed to start: Request initialize failed with message: Incompatible language version 11. Compatibility range 9 through 10.
```
At first, it seemed for me that it may be a CoC issue.
Please see at https://github.com/neoclide/coc.nvim/issues/1610#issuecomment-594515904

**Comment by skovhus** [comment]
@przepompownia Thanks. I think it is tree-sitter related. What does `bash-language-server -v` return?

**Comment by przepompownia** [comment]
Currently I use the master version
```
 $ ./server/bin/main.js -v
Version is 1.9.0
 $ npm -v
6.13.7
```
After `yarn global upgrade` 
```
 $ bash-language-server -v
Version is 1.11.0
 $ ./server/bin/main.js -v
Version is 1.9.0
```
and problem is gone though I still use the local version. Can the local version depend in any way on the packages or executables installed globally?

**Comment by skovhus** [comment]
They cannot depend on global version no. But they problem here might be that you didn’t run a `yarn install` inside the server folder. A dependency needed to be installed after a change I did yesterday. :)
