### ISSUE TITLE
Vim client

### ISSUE THREAD

**Issue by Cosson2017** [mads-hartmann/bash-language-server#3]
How can I use it in vim?
If not, is there plan to support vim?

**Comment by mads-hartmann** [comment]
I'd be happy to have a Vim client. [This](https://github.com/autozimu/LanguageClient-neovim) looks to be the most popular plugin for creating LSP clients in Vim. Seeing as I don't use Vim myself I don't think I'm the right person to implement the client though. I'd be happy to accept a PR that introduces Vim support 😊

**Comment by TrySound** [comment]
[vim-lsp](https://github.com/prabirshrestha/vim-lsp) is quite good.

**Comment by mads-hartmann** [comment]
Fixed by @JakobGM in #19
