### ISSUE TITLE
Use yarn instead of npm (in vscode-client)

### ISSUE THREAD

**Issue by michalpiekarski** [mads-hartmann/bash-language-server#32]
If **yarn** is used for development (see #21 ), maybe it will be also good to make the project itself use **yarn** by default?
Currently (especially in [vscode-client](../tree/master/vscode-client)) **npm** is used by default, and the underlying **bash-language-server** is located using [`npm bin -g`](../tree/master/vscode-client/src/util.ts).

Is it possible to replace (or extend) this by `yarn global bin` etc.?

**Comment by skovhus** [comment]
> project itself use yarn by default?

I would not enforce people to use yarn instead of npm when using the package. 

But do you suggest that when checking where the language server is installed, that we support both npm and yarn? That would make a lot of sense. 👍

**Comment by michalpiekarski** [comment]
Sure. Support for both would be the best option.

**Comment by skovhus** [comment]
`bashIde.path` can now be set. And we hope to ship the server with the client soon.
