### ISSUE TITLE
Dependencies incomplete in development-guide.md

### ISSUE THREAD

**Issue by PromoFaux** [mads-hartmann/bash-language-server#35]
Hi there,

Started looking at building this myself on WSL after attempting to install with `npm i -g bash-language-server` failed.

It may be academic, but in the build process I had to work out for myself that I would need `node` (v6 or greater), `make` and `g++` installed. Probably not unique to WSL, but I'm a bit of a novice when it comes to building things that aren't `.NET` 😉

**Comment by mads-hartmann** [comment]
@PromoFaux I'd be happy to accept a PR with an updated set of prerequisites 👍

**Comment by PromoFaux** [comment]
No problem, can do! Was going to do it anyway, but just wanted to make sure I wasn't being an idiot first 😂
