### ISSUE TITLE
"Can't find bash-language-server on your PATH...." on Windows

### ISSUE THREAD

**Issue by fakuivan** [mads-hartmann/bash-language-server#41]
I've installed the package as advised but the extension fails with this error: 

![image](https://user-images.githubusercontent.com/15100012/39382262-4f88ab94-4a3b-11e8-849a-9b8ec7fcfa89.png)

```
PS C:\Users\fakui> npm i -g bash-language-server
C:\Users\fakui\AppData\Roaming\npm\bash-language-server -> C:\Users\fakui\AppData\Roaming\npm\node_modules\bash-language-server\bin\main.js
+ bash-language-server@1.3.0
updated 1 package in 1.253s
PS C:\Users\fakui> node -v
v10.0.0
PS C:\Users\fakui> (Get-ChildItem Env:Path).Value
C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Common Files\Autodesk Shared\;D:\Program_Files\Strawberry\c\bin;D:\Program_Files\Strawberry\perl\site\bin;D:\Program_Files\Strawberry\perl\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Users\fakui\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\fakui\AppData\Roaming\npm
```

**Comment by skovhus** [comment]
Thanks for reporting this. It might be related to https://github.com/mads-hartmann/bash-language-server/pull/40

**Comment by mads-hartmann** [comment]
@fakuivan Thanks for reporting this. I've released version 1.3.1 which includes #40. Please upgrade the bash language server (`npm i -g bash-language-server`) and re-open if this is still an issue :)

**Comment by fakuivan** [comment]
Nope, still having the same issue. 
```
PS C:\Windows\system32> npm i -g bash-language-server
C:\Users\fakui\AppData\Roaming\npm\bash-language-server -> C:\Users\fakui\AppData\Roaming\npm\node_modules\bash-language-server\bin\main.js
+ bash-language-server@1.3.1
updated 1 package in 5.686s
```

**Comment by mads-hartmann** [comment]
@fakuivan Damn, alright, as I don't have access to windows machines at the moment I'd love your help debugging this issue. Head over to #5 to see what other users have tried.

**Comment by fakuivan** [comment]
@mads-hartmann As far as I understand it, finding the path to the executable is not the problem: 
```powershell
PS C:\Windows\system32> &"$(Join-Path "$(npm.cmd bin -g)" "bash-language-server.cmd")" -v
Version is 1.3.1
```

(if that's what [vscode-client/src/util.ts](https://github.com/mads-hartmann/bash-language-server/blob/master/vscode-client/src/util.ts) does)

**Comment by antonio-petricca** [comment]
I have the same issue:

- Linux Mint 18.3 (Ubuntu 16.04)
- NodeJS 10.1.0
- Bash Language Server 1.3.1

Running it from shell I get this error:

> $ bash-language-server 
> internal/modules/cjs/loader.js:573
>     throw err;
>     ^
> 
> Error: Cannot find module './build/Debug/tree_sitter_runtime_binding'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
>     at Module.require (internal/modules/cjs/loader.js:626:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter/index.js:5:13)
>     at Module._compile (internal/modules/cjs/loader.js:678:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
>     at Module.load (internal/modules/cjs/loader.js:589:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:520:3)

**Comment by fakuivan** [comment]
Just to clarify, this issue is supposed to be open.

**Comment by JoshRagem** [comment]
I think this is failing to require the `Debug` build because of this error (or similar) trying to get the `Release` build:

```
> require('./build/Release/tree_sitter_runtime_binding')
Error: The module '/usr/lib/node_modules/bash-language-server/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

this is my setup with npm:6.1.0 node:v10.2.1 on ubuntu

**Comment by papesch** [comment]
I think it's happening here in main.js. Maybe "spawn" isn't smart enough to find the npm package in Windows
```js
    const childProcess = ChildProcess.spawn(command, args, {
      cwd: projectPath
    });
```

A couple of things to look into:
* https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js
* https://stackoverflow.com/questions/37288044/atom-electron-cant-find-path-of-child-process

**Comment by Amourspirit** [comment]
I am running window 10 home. I am having the same issues.
I tried installing and re-installing 
VS code reports 
![image](https://user-images.githubusercontent.com/4193389/41820467-5de12404-77a0-11e8-935a-fdd1e52b195c.png)

I also tried

> Possible alternatives to Node spawn on windows:

    https://github.com/MarcDiethelm/superspawn
    https://www.npmjs.com/package/cross-spawn

Nothing seems to work still getting same error

`PS C:\WINDOWS\system32> bash-language-server -v`
`Version is 1.3.1`
Any Fix for this?

**Comment by pryorda** [comment]
Having the same issue on mac :/

**Comment by skovhus** [comment]
@pryorda I think that might be an unrelated issue... But how did you install the server? Yarn or npm? And which Shell are you using?

**Comment by pryorda** [comment]
zsh, npm i -g bash-language-server 
```
CO007-mac ➜  /tmp npm i -g bash-language-server
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/bash-language-server
npm ERR! path /usr/local/lib/node_modules/bash-language-server
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/bash-language-server'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/bash-language-server']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/bash-language-server\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/bash-language-server' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dpryor/.npm/_logs/2018-06-30T23_28_24_260Z-debug.log
CO007-mac ➜  /tmp sudo npm i -g bash-language-server
Password:
/usr/local/bin/bash-language-server -> /usr/local/lib/node_modules/bash-language-server/bin/main.js
+ bash-language-server@1.3.1
updated 1 package in 0.752s
CO007-mac ➜  /tmp bash-language-server
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './build/Debug/tree_sitter_runtime_binding'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter/index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
CO007-mac ➜  /tmp
```

**Comment by pryorda** [comment]
Additional Output.
```
521 verbose lifecycle tree-sitter@0.11.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter/node_modules/.bin:/usr/local/lib/node_modules/bash-language-server/node_modules/.bin:/usr/local/lib/node_modules/.bin:/opt/chefdk/bin:/Users/dpryor/.chefdk/gem/ruby/2.4.0/bin:/opt/chefdk/embedded/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dpryor/go/bin:/usr/lib/go-1.9/bin:/sbin/bin:/snap/bin:/Users/dpryor/.local/bin:/usr/local/opt/go@1.9/libexec/bin:/opt/local/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/bin:/opt/chefdk/gitbin
522 verbose lifecycle tree-sitter@0.11.2~install: CWD: /usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter
523 silly lifecycle tree-sitter@0.11.2~install: Args: [ '-c', 'node-gyp rebuild' ]
524 silly lifecycle tree-sitter@0.11.2~install: Returned: code: 1  signal: null
525 info lifecycle tree-sitter@0.11.2~install: Failed to exec install script
526 timing action:install Completed in 469ms
527 verbose unlock done using /Users/dpryor/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
528 timing stage:rollbackFailedOptional Completed in 73ms
529 timing stage:runTopLevelLifecycles Completed in 4730ms
530 verbose stack Error: tree-sitter@0.11.2 install: `node-gyp rebuild`
530 verbose stack Exit status 1
530 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
530 verbose stack     at EventEmitter.emit (events.js:182:13)
530 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
530 verbose stack     at ChildProcess.emit (events.js:182:13)
530 verbose stack     at maybeClose (internal/child_process.js:961:16)
530 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
531 verbose pkgid tree-sitter@0.11.2
532 verbose cwd /usr/local/lib/node_modules
533 verbose Darwin 17.6.0
534 verbose argv "/usr/local/Cellar/node/10.5.0_1/bin/node" "/usr/local/bin/npm" "i" "-g" "bash-language-server"
535 verbose node v10.5.0
536 verbose npm  v6.1.0
537 error code ELIFECYCLE
538 error errno 1
539 error tree-sitter@0.11.2 install: `node-gyp rebuild`
539 error Exit status 1
540 error Failed at the tree-sitter@0.11.2 install script.
540 error This is probably not a problem with npm. There is likely additional logging output above.
541 verbose exit [ 1, true ]
```

**Comment by pryorda** [comment]
Looks like I had to install Xcode, accept the license, blah blah.

Thanks

**Comment by mads-hartmann** [comment]
I've just released version 1.3.1 of the VSCode extension which adds a new configuration option `bashIde.path`.  Please see if you can use that to run it on Windows. As for Atom I think it's a good idea to use cross-spawn.

**Comment by Lucretia** [comment]
I'm on Gentoo, it can't seem to find the server, because it's dumping the following:

    module.js:549
        throw err;
        ^

    Error: Cannot find module './build/Debug/tree_sitter_runtime_binding'
        at Function.Module._resolveFilename (module.js:547:15)
        at Function.Module._load (module.js:474:25)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/usr/lib64/node_modules/bash-language-server/node_modules/tree-sitter/index.js:5:13)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)

Why is it wanting a debug module?

**Comment by mads-hartmann** [comment]
@Lucretia Are you setting the path explicitly using the new config options?

I'm not sure about the missing debug module. @maxbrunsfeld any idea?

**Comment by Lucretia** [comment]
@mads-hartmann I've had the option not set and had it set, same issue. Running the bash-language-server directly produces the above error.

**Comment by pryorda** [comment]
@Lucretia How did you install bls?

**Comment by maxbrunsfeld** [comment]
> Why is it wanting a debug module?

I think that on an older version of Tree-sitter, that error was thrown even if the `Release` module failed to load because it would try to 'fall back' to the Debug module. That's been fixed for more recent Tree-sitter versions.

> I'm not sure about the missing debug module. maxbrunsfeld any idea?

I'm guessing that people are installing your module with `npm` manually, so the native modules are not getting compiled against the correct version of node.js?

**Comment by Lucretia** [comment]
@pryorda ```npm i -g bash-language-server```as root (on gentoo).

**Comment by pryorda** [comment]
Have you tried to build from source to see what happens?

**Comment by antonio-petricca** [comment]
Version 1.3.1 on Ubuntu 18.04 works for me! :+1:

**Comment by maxbrunsfeld** [comment]
@mads-hartmann Once [this PR] lands, we could do something similar for `tree-sitter-bash`, and then users would be able to install the package without having a C compiler toolchain.

**Comment by mads-hartmann** [comment]
@maxbrunsfeld I think you forgot the link? 😊

**Comment by maxbrunsfeld** [comment]
🤦‍♂️ thanks. I added it above.

**Comment by mads-hartmann** [comment]
@maxbrunsfeld Just had a look - that would be amazing - the current install process for this project is way more complicated then I would've liked

**Comment by thehandcoder** [comment]
If you change the prefix before installing, it works.  You can specify your global lib folder.  For example, I did `npm config set prefix="/usr/local/"` before installing and that fixed the problem

**Comment by skovhus** [comment]
@fakuivan @thehandcoder please try to install the latest `bash-language-server` by running `npm install -g bash-language-server`. We hope to have fixed the issue in version 1.5.1 by the help from @wingrunr21.

**Comment by alexford-bg** [comment]
I was having this problem as well, and oddly, by running the following command it fixed it for me on Ubuntu 18.04, VS Code 1.27.2:
```bash
sudo npm i -g bash-language-server tree-sitter tree-sitter-bash --unsafe-perm
```
I ran the install command for each of the modules separately, and that didn't work... it was only when I did it all at once did it resolve things.

**Comment by vjtc0n** [comment]
@alexford-bg Thank you so much, work like a charm on MacOSX, too.

**Comment by Lucretia** [comment]
```
# npm install -g bash-language-server
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/whatwg-mimetype/-/whatwg-mimetype-2.2.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-02T14_02_39_858Z-debug.log
```
The tail of that log is:
```
885 silly pacote prebuild-install@https://registry.npmjs.org/prebuild-install/-/prebuild-install-5.2.0.tgz extracted in 6514ms
886 verbose unlock done using /root/.npm/_locks/staging-5416abac55ed2dd0.lock for /usr/lib64/node_modules/.staging
887 verbose type system
888 verbose stack FetchError: request to https://registry.npmjs.org/whatwg-mimetype/-/whatwg-mimetype-2.2.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443
888 verbose stack     at ClientRequest.req.on.err (/usr/lib64/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
888 verbose stack     at ClientRequest.emit (events.js:180:13)
888 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:395:9)
888 verbose stack     at TLSSocket.emit (events.js:180:13)
888 verbose stack     at emitErrorNT (internal/streams/destroy.js:64:8)
888 verbose stack     at process._tickCallback (internal/process/next_tick.js:178:19)
889 verbose cwd /root
890 verbose Linux 4.19.0-rc4
891 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bash-language-server"
892 verbose node v9.11.2
893 verbose npm  v5.6.0
894 error code EAI_AGAIN
895 error errno EAI_AGAIN
896 error request to https://registry.npmjs.org/whatwg-mimetype/-/whatwg-mimetype-2.2.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443
897 verbose exit [ 1, true ]
```

**Comment by Cavsfan-Linux** [comment]
> I was having this problem as well, and oddly, by running the following command it fixed it for me on Ubuntu 18.04, VS Code 1.27.2:
> 
> ```shell
> sudo npm i -g bash-language-server tree-sitter tree-sitter-bash --unsafe-perm
> ```
> 
> I ran the install command for each of the modules separately, and that didn't work... it was only when I did it all at once did it resolve things.

Thank you! That is THE only thing I could find that worked.

**Comment by nottoseethesun** [comment]
Setting an absolute path for `Bash Ide: Path` worked for me.

**Comment by skovhus** [comment]
@nottoseethesun just to be clear, where did you set this? It seems bash-language server and other npm scripts are not on your path....

**Comment by nottoseethesun** [comment]
@skovhus I set it in the VSCode Prefs. I did put the server in my path, and I did also do the "hack" of installing the dep's globally as well.  I am using `nvm`, but I used the correct path to the binary.   For me anyway, using the shell path didn't work.

**Comment by mystic-cg** [comment]
I have the same problem. Although I had installed bash-language-server

**Comment by briancrink** [comment]
incurred this problem on mac Catalina, have Xcode 10.2.1 installed with accepted license.

**Comment by chrisduong** [comment]
Still not working same Brian's report.

**Comment by skovhus** [comment]
With the new version (1.4.0) of the VS Code extension, we got rid of the manual npm install step of the bash-language-server. Hopefully, this will resolve npm installation issues. :) 

The latest version of `bash-language-server` (the npm package) should also be easier to install.

Let me know if this solves the issues.
