### ISSUE TITLE
Explainshell integration

### ISSUE THREAD

**Issue by chrismwendt** [mads-hartmann/bash-language-server#42]
Check out Explainshell:

https://explainshell.com/explain?cmd=tar%20xzvf%20archive.tar.gz

![image](https://user-images.githubusercontent.com/1387653/40573108-c9862070-6070-11e8-9012-705d68b42a67.png)

Could Explainshell be integrated into bash-language-server?

**Comment by mads-hartmann** [comment]
@chrismwendt That's definitely a cool tool. I'd be happy to accept a contribution that integrate this in some form or other 👍

**Comment by chrismwendt** [comment]
It turns out explainshell is not going to be very easy to integrate, unless the JSON API https://github.com/idank/explainshell/pull/125 gets merged in, and it's ok to make HTTP requests to explainshell.com from this language server.

explainshell is written in Python, and requires MongoDB as a backing store. It also has a large database (100s of MB) of man pages https://github.com/idank/explainshell-manpages that would need to be distributed (if we want to avoid the potential JSON API on explainshell.com).

Another alternative is to put explainshell in a Docker container along with this language server and communicate over TCP. Sourcegraph has already done the Docker and TCP parts: https://github.com/sourcegraph/lsp-adapter/tree/master/dockerfiles/bash

**Comment by mads-hartmann** [comment]
Awesome that you're using it over at Sourcegraph 🙌 

I'd prefer using their JSON api if they'll allow it once it's ready. I think the Docker approach is interesting but I think the setup might be a bit too complicated - I'm concerned it would eat up too many resources on the developers computers 🙂
