### ISSUE TITLE
! char in ${!var} shows as invalid

### ISSUE THREAD

**Issue by hirenvadalia** [mads-hartmann/bash-language-server#43]
I am using Bash IDE in VSCode and below code shows as invalid code while it is valid code 
```bash
TEST_VAR=1
TEST_VAR1=1
declare -a list_of_variables=("TEST_VAR" "TEST_VAR1")
for var in ${list_of_variables[@]}
do
	echo "${var}=${!var}"
done
```
When I hover over `!` char then it show 'Failed to parse expression' in tooltip

**Comment by mads-hartmann** [comment]
This is definitely a grammar problem. I'll try to update to `0.11.2` and see if it's still an issue there :)

**Comment by hirenvadalia** [comment]
Hey @mads-hartmann Any update on this?

**Comment by skovhus** [comment]
I tried upgrading to the latest version `tree-sitter-bash@0.11.2`, but I still see this issue. 

It seems to be this one https://github.com/tree-sitter/tree-sitter-bash/issues/18

**Comment by achekulaev** [comment]
Yes, the issue is still there.

**Comment by christopherdwhite** [comment]
I opened an issue for this problem https://github.com/tree-sitter/tree-sitter-bash/issues/21

**Comment by skovhus** [comment]
@christopherdwhite thanks for creating the issue in tree-sitter-bash!
