### ISSUE TITLE
>&2 is not recognized as valid syntax

### ISSUE THREAD

**Issue by chrismwendt** [mads-hartmann/bash-language-server#44]
![image](https://user-images.githubusercontent.com/1387653/40590084-b383ee22-61ad-11e8-838a-16503450208a.png)

**Comment by mads-hartmann** [comment]
@chrismwendt Thanks for reporting. This is a problem with the underlying grammar. We're two minor versions behind. I'll try to upgrade next week and see if that fixes it 👍

**Comment by chrismwendt** [comment]
There are tons of weird bits of valid Bash in https://github.com/creationix/nvm/blob/master/nvm.sh that aren't recognized, in case you're looking for more examples 🙂

**Comment by mads-hartmann** [comment]
The grammar is still very much a work in progress :) Once I've upgraded to the newest version it would be nice to create stand-alone issues for broken cases over at https://github.com/tree-sitter/tree-sitter-bash/issues

**Comment by skovhus** [comment]
The specific case `>&2` has been fixed in the latest version.
