### ISSUE TITLE
Can't install on Manjaro Linux 17.10

### ISSUE THREAD

**Issue by EvanWashkow** [mads-hartmann/bash-language-server#48]
For the life of me, I can't get this package to install in NPM. Maybe I'm just doing this really incredibly wrong, or my system needs to be configured differently.

1. **Install command**: `sudo npm i -g bash-language-server`

2. While the project is installing, I see TONS of these error messages:
```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/bash-language-server/node_modules/tree-sitter/.node-gyp/10.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/bash-language-server/node_modules/tree-sitter/.node-gyp"
```

3. After the installer finishes, I get a fatal error:
[npm-error.txt](https://github.com/mads-hartmann/bash-language-server/files/2091205/npm-error.txt)

4. Here's the debug.log:
[2018-06-11T18_11_37_553Z-debug.log](https://github.com/mads-hartmann/bash-language-server/files/2091214/2018-06-11T18_11_37_553Z-debug.log)

**Comment by mads-hartmann** [comment]
@EvanWashkow You shouldn't need to install it with `sudo` - what happens if you don't use sudo?

**Comment by EvanWashkow** [comment]
@mads-hartmann So, I tried that as well (and I ran it again, just to see the output).

```
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/evan/.npm/_logs/2018-06-12T22_07_13_648Z-debug.log
```

Here's that debug.log mentioned:
[2018-06-12T22_07_13_648Z-debug.log](https://github.com/mads-hartmann/bash-language-server/files/2095969/2018-06-12T22_07_13_648Z-debug.log)

**Comment by EvanWashkow** [comment]
^ And, that's why I thought I needed to run as `sudo`, since it's trying to install those node modules in the `/usr/lib/node_modules` directory: which is root-only.

**Comment by mads-hartmann** [comment]
@EvanWashkow It's a bit hard to debug these thing remotely - can you see if this guide helps you? 😊https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by EvanWashkow** [comment]
Okay. Thank you.

**Comment by ragouel** [comment]
This is a node configuration issue. 
Do this to fix it:
`cd ~ && mkdir .node_modules_global && npm config set prefix=$HOME/.node_modules_global && npm config set prefix=$HOME/.node_modules_global`

It's generally discouraged to install extensions outside the home directory, the above one liner changes the global path from 

> /usr

 to 

> /home/user/.node_modules_global
