### ISSUE TITLE
Prefer explainshell responses when available

### ISSUE THREAD

**Issue by chrismwendt** [mads-hartmann/bash-language-server#51]
For the file at https://sourcegraph.com/github.com/nodejs/node/-/blob/tools/update-babel-eslint.sh:

- `npm init` is properly documented but the `install` in `npm install` is interpreted as the global `install` Unix command not the `npm install` subcommand

This happens because explainshell is currently [a fallback plan](https://sourcegraph.com/github.com/mads-hartmann/bash-language-server@cfdc070f52847bb6f928769cf2a955cdf44e3e87/-/blob/server/src/server.ts#L128), but probably should be the first choice.

**Comment by mads-hartmann** [comment]
@chrismwendt I'm totally fine with switching the order ☺️
