### ISSUE TITLE
Add ALE to the README Installation section

### ISSUE THREAD

**Issue by w0rp** [mads-hartmann/bash-language-server#55]
[ALE](https://github.com/w0rp/ale) Now supports `bash-language-sever` out of the box, if installed, and requires no configuration for it to start running.

**Comment by skovhus** [comment]
Nice! Do you have time to submit a PR? :)

**Comment by w0rp** [comment]
I don't have the time myself.

**Comment by keith** [comment]
Submitted here https://github.com/mads-hartmann/bash-language-server/pull/64

**Comment by mads-hartmann** [comment]
Fixed in #64
