### ISSUE TITLE
Improve code completetion

### ISSUE THREAD

**Issue by skovhus** [mads-hartmann/bash-language-server#6]
Just installed this, and it works really nicely! Jump to definition and parsing errors are really nice.

Would be nice to improve the code completions. VS Code per default autocompletes on words, but this is disabled when using a language server I guess. : )

Ideas from the TODO file:
- [x] Based on symbols in the file
- [ ] Based on all symbols in the workspace
- [x] Based on programs in your PATH
- [ ] path completions, e.g. on `foo/b` should return `bar` if you have a file named `bar` inside of a folder named `foo`

Ideas from the [source code ](https://github.com/mads-hartmann/bash-language-server/blob/master/server/src/server.ts#L166):
- [x] Look up man pages for commands
- [x] For builtins look up the docs
- [ ] For functions, parse their comments?

**Comment by mads-hartmann** [comment]
@skovhus I'm working on completions based on your PATH on an experimental branch at the moment :)

**Comment by mads-hartmann** [comment]
@skovhus The prototype is here in case you want to work on it 😉https://github.com/mads-hartmann/bash-language-server/commit/c90b1639fc4e03f07205740cf217d39365ea70c5

**Comment by skovhus** [comment]
Improvement are out in the latest version.
