### ISSUE TITLE
Use prebuild to avoid external installing in vscode

### ISSUE THREAD

**Issue by mads-hartmann** [mads-hartmann/bash-language-server#62]
Investigate if we can use prebuild and prebuild-install and then have the bash-language-server as a direct dependency on the vscode extension. The goal is to avoid having to install the server separately for vscode.

- [prebuild](https://github.com/prebuild/prebuild)
- [prebuild-install](https://github.com/prebuild/prebuild-install)

**Comment by mads-hartmann** [comment]
@skovhus I'm not entirely sure - I don't fully grasp the build process of native node modules to be honest. I think we might be able to use `prebuild` to expose an already natively compiled version of our package and its dependencies (so we would be duplicating some of the work happening in that PR). We could also just wait and see if it just works once that PR is merged ;)

**Comment by wingrunr21** [comment]
@mads-hartmann it should "just work" (I hope) once the PR is merged. I'm using `tree-sitter` in `vscode-ruby` to build a new language server there.

**Comment by mads-hartmann** [comment]
@wingrunr21 Awesome - that's going to drastically reduce the number of issues we get I hope 👏

**Comment by maxbrunsfeld** [comment]
@mads-hartmann The pre-built binaries are up. Users should be able to install v0.13.1 of both modules without a compiler toolchain.

* https://github.com/tree-sitter/node-tree-sitter/releases/tag/v0.13.1
* https://github.com/tree-sitter/tree-sitter-bash/releases/tag/v0.13.1

**Comment by mads-hartmann** [comment]
Fixed  in bash-language-server v. 1.5.1
