### ISSUE TITLE
Three-expression bash for loops syntax

### ISSUE THREAD

**Issue by bunam** [mads-hartmann/bash-language-server#66]
failed to parse expression for : 
```bash
for (( i=2 ; i <= n ; i++ )) {
	echo $i
}
```

**Comment by skovhus** [comment]
@bunam thanks for reporting this. 

Do you mind creating an issue here https://github.com/tree-sitter/tree-sitter-bash? :)

**Comment by bunam** [comment]
https://github.com/tree-sitter/tree-sitter-bash/issues/22
