### ISSUE TITLE
Merge with `vscode-bash-debug`?

### ISSUE THREAD

**Issue by kolya-ay** [mads-hartmann/bash-language-server#7]
It would be cool if you coordinated your efforts with @rogalmic as soon as the extension already has such cool name

**Comment by mads-hartmann** [comment]
@kolya-ay Debugging isn't part of the language server specification (as far as I can tell) at the moment so at least for now it makes sense to keep to projects separately ☺️

**Comment by rcjsuen** [comment]
I think this comes down to what this VS Code extension offers. If all it's doing is launching the language server then I feel like that code should be moved to the vscode-bash-debug project and then this repository would just be for hosting the language server's code.

The vscode-bash-debug team might want to change its name then though if it's offering both debugging capabilities and rich editor features for bash scripts.

**Comment by kolya-ay** [comment]
@rcjsuen, that's exactly what I mean. 

There is another [protocol for debugging](https://github.com/Microsoft/vscode-debugadapter-node/wiki/VS-Code-Debug-Protocol-Implementations) which should be implemented in `vscode-bash-debug`. I just wanted extensions to be assembled under one roof to produce real vscode-bash-ide;)

**Comment by rogalmic** [comment]
Instead of merging code and making all-in-one extension, maybe `extensionDependencies` entry pointing to debugger is an option?
(https://code.visualstudio.com/docs/extensionAPI/extension-manifest)

Also, one excellent tool is shellcheck, which helps a lot with common errors in bash scripts (there is already extension for that).

**Comment by mads-hartmann** [comment]
@rogalmic that's interesting. 

@kolya-ay @rcjsuen For now I'll focus on trying to make the bash-language-server great. There's still a ton of work left (it's very much just a prototype at the moment). Once it's a bit more mature I'm open to collaborate with other projects :)

**Comment by rcjsuen** [comment]
@mads-hartmann That's totally fair. I think you get the most value by creating a good language server for clients to use anyway. If your language server is good other people will create extensions and plug-ins that delegate to it anyway and that'll naturally relieve you of having to maintain those things yourself. :)

Good luck with the project!
