### ISSUE TITLE
Improve parsing error messages

### ISSUE THREAD

**Issue by skovhus** [mads-hartmann/bash-language-server#74]
We can treesitter to improve the parsing error messages:
- `SyntaxNode.hasError()` API to show if parts of a script fail to parse (see https://github.com/tree-sitter/tree-sitter-bash/issues/27#issuecomment-410867036)
- error recovery to show more specific errors if a specific node is missing (see https://github.com/tree-sitter/tree-sitter-bash/issues/27#issuecomment-410865045)

**Comment by mads-hartmann** [comment]
@skovhus That's really cool 👍
