### ISSUE TITLE
Extension reports errors everywhere, not just where they happen

### ISSUE THREAD

**Issue by achekulaev** [mads-hartmann/bash-language-server#77]
This one seems to be related to this extension rather then tree-sitter, correct me if I am wrong. 

Bash IDE highlights the whole function (or even the whole file!) as erroneous, despite parsing error actually happens only in a single line of the function. Example:

<img width="382" alt="ex3" src="https://user-images.githubusercontent.com/402007/44422884-7134ff00-a552-11e8-87e3-db0a7c2ecba2.png">

And even worse when it is the whole file

<img width="343" alt="ex2" src="https://user-images.githubusercontent.com/402007/44422863-5bbfd500-a552-11e8-982f-c5f8923bedbb.png">

So the issue here is the line `[[ "$x" == *"something something"* ]]`. If I remove it, the underline will be gone. It is a Tree-sitter issue and this is fine, I will report it and hope they will fix it.

What is puzzling here is why Bash IDE has highlighted the whole file in red, rendering it impossible to spot the problematic place. I would expect Bash IDE to only highlight the line, where the error has happened. **Maybe** also the function name. 

But not all the lines in the function and definitely not all the lines in the file. 

As bash developer I really want to see those highlights, because it helps to spot error early, but they need to be meaningful to be useful.

**Comment by skovhus** [comment]
Thanks for creating this issue. We are working on better error highlighting based on an improved version of the grammar. 

We can actually improve this a lot by looking if a node `isMissing` or `hasError`.

**Comment by skovhus** [comment]
@achekulaev can you do a:
`bash-language-server --version`

**Comment by achekulaev** [comment]
```
§ bash-language-server --version
Version is 1.5.2
```

**Comment by achekulaev** [comment]
Please tell if there is anything else that will help to resolve the issue.

**Comment by skovhus** [comment]
Until we improve the parser you disable the error from showing up by setting the config parameter: `bashIde.highlightParsingErrors`. 

With they latest version you still see the two errors reported above?

**Comment by achekulaev** [comment]
Yes for me the error is still there.

**Comment by Yanpas** [comment]
Same issue applies to
```
if ((${#aaa[@]} == 0)); then
fi
```

**Comment by Yanpas** [comment]
There are seem to be updates to grammar
https://github.com/tree-sitter/tree-sitter-bash/issues/32

**Comment by skovhus** [comment]
@Yanpas 👍. Was just about to create a PR. :)

**Comment by skovhus** [comment]
@achekulaev Please reopen if this still is a problem after upgrading the `bash-language-server`

**Comment by Yanpas** [comment]
I face the same issues still because of complex bash grammar
(Function body range is parsed incorrectly) https://github.com/tree-sitter/tree-sitter-bash/issues/35
(Error while parsing stream redirection inside dollar-parentheses) https://github.com/tree-sitter/tree-sitter-bash/issues/34
