### ISSUE TITLE
Failure to parse array index expansion

### ISSUE THREAD

**Issue by SidIcarus** [mads-hartmann/bash-language-server#81]
```bash
local key
local -A assArray=(['a']=0 ['b']=1)
for key in "${!assArray[@]}"; do
  printf 'Key: %s, Value: %s\n' "${key}" "${assArray[${key}]}"
done
```

`"${!assArray[@]}"` Fails to parse due to the index expansion operator, `!`.

This feature was added to bash in version 3.0.

**Comment by skovhus** [comment]
Thanks for reporting. This one should actually go into https://github.com/tree-sitter/tree-sitter-bash, but I cannot reproduce this error with the latest version of the language server. 

Can you try to reproduce after doing `npm i -g bash-language-server` and reload VS Code?

**Comment by SidIcarus** [comment]
@skovhus

I updated the language server and it appears to have been fixed. I presume this ticket should be closed?

**Comment by skovhus** [comment]
Thanks!
