### ISSUE TITLE
Not support for Emacs ? 

### ISSUE THREAD

**Issue by dinuscxj** [mads-hartmann/bash-language-server#85]
File mode specification error: (lsp-timed-out-error)

**Comment by mads-hartmann** [comment]
@dinuscxj There's nothing editor specific about the language server. It's just a process that you start and communicate with. If it doesn't work with Emacs it's your Emacs configuration that's faulty somehow :)

I'll change the issue to be a feature request to add docs for how to run it with Emacs.

**Comment by mads-hartmann** [comment]
I've added a feature request for an example of how to use it with Emacs. https://github.com/mads-hartmann/bash-language-server/issues/86
