### ISSUE TITLE
Trouble installing on Mac OSX

### ISSUE THREAD

**Issue by NorthboundTrain** [mads-hartmann/bash-language-server#87]
VS Code: 1.28.2
OSX: 10.12.6
BashIDE: 1.3.3
NPM: 5.6.0 (installed via MacPorts)
MacPorts: 2.4.2
=========
The output is:

mymac:~ root# npm install -g bash-language-server
/opt/local/bin/bash-language-server -> /opt/local/lib/node_modules/bash-language-server/bin/main.js

> tree-sitter@0.13.17 install /opt/local/lib/node_modules/bash-language-server/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/var/root/.npm'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/local/lib/node_modules/bash-language-server/node_modules/tree-sitter/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/local/lib/node_modules/bash-language-server/node_modules/tree-sitter
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter@0.13.17 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter@0.13.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
=========

Thanks for the help!

**Comment by skovhus** [comment]
This is an issue with your npm installation. A workaround is to use `sudo`. 

Let me know if that worked for you. Thanks.

**Comment by NorthboundTrain** [comment]
It was indeed a bad npm install (via MacPorts). I removed all of that and then installed directly from nodejs.org and it all works now -- thanks!
