### ISSUE TITLE
Multiple parsing problems

### ISSUE THREAD

**Issue by achekulaev** [mads-hartmann/bash-language-server#9]
There is a fully valid Bash script https://github.com/docksal/docksal/blob/develop/bin/fin
When I load it in VSCode that uses bash language server it reports 111 issues.

**Comment by mads-hartmann** [comment]
@achekulaev Thanks! I'll take a look. The parse errors are produced by the underlying parser which is [tree-sitter/tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash) but we're a few versions behind their latest release so I'll try to update the version and if there are still problems I'll create an issue in their repository and try to fix it there :)

**Comment by achekulaev** [comment]
Gotcha, thanks.

**Comment by mads-hartmann** [comment]
@achekulaev I've published a new version of bash-language-server (`1.1.2`) that uses the newest version of `tree-sitter-bash`. However there are still a ton of parsing errors (just as many it seems). If you're up for it it would be awesome if you could locate the parsing problems at create issues over at [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash)

**Comment by achekulaev** [comment]
@mads-hartmann is there any howto how to locate them? I ended up here only because I had installed https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode 

In VSCode the whole file is underlined with a single red line, so I don't even know how to single-out the errors.

<img width="1440" alt="fin 2018-03-19 15-26-51" src="https://user-images.githubusercontent.com/402007/37617593-fb672920-2b89-11e8-9e28-9d81fbcbd3e5.png">

**Comment by achekulaev** [comment]
Okay I was able to manually single out some issues and posted them there.

**Comment by mads-hartmann** [comment]
@achekulaev Since version 1.3.2 you've been able to disable the highlighting of errors as documented here: https://github.com/mads-hartmann/bash-language-server/blob/master/vscode-client/CHANGELOG.md#132 :) We're continuously working on improving the grammar.

**Comment by achekulaev** [comment]
Thanks for notice, though I don't think it makes sense :) I would like grammar check to work, just support all those things.
It would also help a lot if it highlighted the correct lines, since at the moment it highlights the whole file instead.
