### ISSUE TITLE
Bash IDE server crashes repeatedly

### ISSUE THREAD

**Issue by NorthboundTrain** [mads-hartmann/bash-language-server#90]
VS Code: 1.28.2
Bash-IDE: 1.3.3
bash-language-server: 1.5.4

The error message is:

`The Bash IDE server crashed 5 times in the last 3 minutes. The server will not be restarted.`

and the output is:

```
Initialized server v. 1.5.4 for file:///tmp/files/main
Analyzing file:///tmp/files/main/foo.sh
Analyzing file:///tmp/files/main/bar.sh
Analyzing file:///tmp/files/main/prebaz.sh
Analyzing file:///tmp/files/main/baz.sh
Analyzing file:///tmp/files/main/subdir/prefoo.sh
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/tmp/files/main/sibdir/prefoo.sh'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at paths.forEach.p (/home/node_modules/bash-language-server/out/analyser.js:64:91)
    at Array.forEach (<anonymous>)
    at glob (/home/node_modules/bash-language-server/out/analyser.js:60:27)
    at f (/home/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:182:13)
    at Glob._finish (/home/node_modules/glob/glob.js:197:8)
    at done (/home/node_modules/glob/glob.js:182:14)
[Error - 7:58:49 AM] Connection to server got closed. Server will not be restarted.
```

The file in question (prefoo.sh) is not even open, but its parent directory (subdir) is part of the workspace, so I guess it scans everything? The file is not a bash file, though, it's a ksh file (via she-bang line).

Is there any way to prevent bash-language-server from scanning files that are not loaded? Is there any way to have it ignore specific files? Is there any way to have it ignore files based on the she-bang line?

Thanks!

**Comment by skovhus** [comment]
Thanks for reporting this.

> Is there any way to prevent bash-language-server from scanning files that are not loaded? Is there any way to have it ignore specific files? Is there any way to have it ignore files based on the she-bang line?

Scanning the files shouldn't be a problem, and we use it for references across files. But the problem here is actually that we don't respect the she-bang line. That bug is actually documented here: https://github.com/mads-hartmann/bash-language-server/issues/47
