### ISSUE TITLE
Failed to parse expression ";;&"

### ISSUE THREAD

**Issue by niklasholm** [mads-hartmann/bash-language-server#99]
![image](https://user-images.githubusercontent.com/572511/52001626-2b487380-24c0-11e9-9c8b-5d2ff2a3892a.png)

**Comment by skovhus** [comment]
Thanks! This is an error in the underlying parser. 

Can you create a ticket here: https://github.com/tree-sitter/tree-sitter-bash ?

**Comment by niklasholm** [comment]
Oh, okay. Seems to be reported [here](tree-sitter/tree-sitter-bash#40) but no response yet.
